### ISSUE TITLE
Assets are missing

### ISSUE THREAD

**Issue by ChaoticRoman** [matejvrba/Sietor#1]
Attempt to build the project failed with:
```
error: failed to run custom build command for `sietor v0.1.0 (/home/roman/projects/Sietor)`

Caused by:
  process didn't exit successfully: `/home/roman/projects/Sietor/target/debug/build/sietor-8afc410bbadcf5f3/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:45:27:
  called `Result::unwrap()` on an `Err` value: Error { depth: 0, inner: Io { path: Some("/home/roman/projects/Sietor/assets"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
Assets indeed are missing:
``` 
$ ls /home/roman/projects/Sietor/assets
ls: cannot access '/home/roman/projects/Sietor/assets': No such file or directory
```

**Comment by matej-vrba** [comment]
Hmm, I got different error caused by unused vec-2-10-10-10 crate (which should be fixed now). I also removed references to `assets` dir from build script as it's not used, so that _should_ fix your error.

You will probably get another error caused by missing fotn. At the moment font needs to be placed in the directory you're launching it from (likely project root). Adjust font name in `src/buffer.rs:130`.

Also the project barely does anything. It is vim inspired - you can use arrows or `hjkl` to move cursor, `i` to enter insert mode and `<ESC>` to return to normal mode.

Setting environment variable `RUST_LOG` enables logging. There are multiple levels of logs, setting it to "trace" enables all logging (`export RUST_LOG=trace`).

**Comment by matej-vrba** [comment]
If you want I can send you the font used, but I won't add it to the repo because copyright.

**Comment by ChaoticRoman** [comment]
Now it builds! You are right about the font but I just got first random open source font I have found using
```
wget https://github.com/kiwi0fruit/open-fonts/raw/master/Fonts/SourceCodePro/SourceCodePro-BlackIt.ttf -O font.ttf
```
and did this
```diff
diff --git a/src/buffer.rs b/src/buffer.rs
index 40fdd50..e0e576c 100644
--- a/src/buffer.rs
+++ b/src/buffer.rs
@@ -126,8 +126,8 @@ impl TextBuffer<'_> {
         view_pos: Option<(usize, usize)>,
         screen_scale: f32,
     ) -> Self {
-        trace!("Loading font \"./Hack-Regular.ttf\"");
-        let font_path = std::env::current_dir().unwrap().join("./Hack-Regular.ttf");
+        trace!("Loading font");
+        let font_path = std::env::current_dir().unwrap().join("./font.ttf");
         let data = std::fs::read(&font_path).unwrap();
         let font = Font::try_from_vec(data).unwrap();
         let mut buf = TextBuffer {
```
And it works! 

I was just interested how much lines of code it takes to get some basic GUI working in Rust and dependencies used...
